version: "3"

services:
    nginx:
        container_name: nginx
        build: ./nginx
        image: docker-server/nginx
        restart: always
        ports:
          - "80:80"
        volumes:
          - ./find_missing_people:/srv/docker-server
          - ./log:/var/log/nginx
        depends_on:
          - django

    django:
        container_name: django
        build: ./find_missing_people
        image: docker-server/django
        restart: always
        command: uwsgi --ini uwsgi.ini
        volumes:
          - ./find_missing_people:/srv/docker-server
          - ./log:/var/log/uwsgi
        depends_on:
          - db
          
    db:
        container_name: db
        build: ./postgresql
        image: docker-server/db
        restart: always
        volumes:
          - ./postgresql/data:/var/lib/postgresql/data
        ports:
          - 5432:5432
        environment:
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
