name: Unittest

on: [push, pull_request]

jobs:
  build:
    name: CI workflow
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: findmissingpeople
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          cd find_missing_people
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Set up Database
        run: |
          sudo apt-get install -y postgresql postgresql-client libpq-dev

      - name: Migrations
        run: |
          cd find_missing_people
          python manage.py makemigrations
          python manage.py migrate

      - name: UnitTest
        run: |
          cd find_missing_people
          python manage.py test
        

